// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiron.Data.Context;

namespace Quiron.Data.Migrations
{
    [DbContext(typeof(QuironContext))]
    [Migration("20200305192619_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quiron.Domain.Entities.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Espaco");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1dad22f-7745-445a-bd37-ab1b5bf6f993"),
                            Descricao = "Salão de Festas"
                        },
                        new
                        {
                            Id = new Guid("efdd12fe-6a7f-482f-af2f-c2395188bcc7"),
                            Descricao = "Piscina"
                        },
                        new
                        {
                            Id = new Guid("c1d514db-6c2b-47eb-bbe2-b6a3cc3ec25b"),
                            Descricao = "Churrasqueira"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
