// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiron.Data.Context;

namespace Quiron.Data.Migrations
{
    [DbContext(typeof(QuironContext))]
    [Migration("20200612192139_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Quiron.Domain.Entities.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Espaco");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2104499d-ed03-4a2a-9995-c21c6c23ceaa"),
                            Descricao = "Salão de Festas"
                        },
                        new
                        {
                            Id = new Guid("872a4818-ab40-4950-a297-9ea81983495f"),
                            Descricao = "Piscina"
                        },
                        new
                        {
                            Id = new Guid("9a4ae6c2-0e91-459e-9d2b-fb755c952195"),
                            Descricao = "Churrasqueira"
                        });
                });

            modelBuilder.Entity("Quiron.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24f63b78-c0da-4f6c-a817-14844384edc4"),
                            Descricao = "Ceara",
                            Uf = "CE"
                        },
                        new
                        {
                            Id = new Guid("970bfe8c-5050-4a43-bc9a-ed0a38098691"),
                            Descricao = "Sao Paulo",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = new Guid("fa50ba2f-b9c8-4092-bf0f-588cca61463c"),
                            Descricao = "Rio de Janeiro",
                            Uf = "RJ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
