// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiron.Data.Context;

namespace Quiron.Data.Migrations
{
    [DbContext(typeof(QuironContext))]
    partial class QuironContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Quiron.Domain.Entities.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Espaco");

                    b.HasData(
                        new
                        {
                            Id = new Guid("699009e2-050a-43ed-bf00-8b383933b2d5"),
                            Descricao = "Salão de Festas"
                        },
                        new
                        {
                            Id = new Guid("4e58e765-95ff-4815-8968-3c5199053b20"),
                            Descricao = "Piscina"
                        },
                        new
                        {
                            Id = new Guid("bb12a32a-97f2-451e-8bbd-84ee3abbb39a"),
                            Descricao = "Churrasqueira"
                        });
                });

            modelBuilder.Entity("Quiron.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estado");

                    b.HasData(
                        new
                        {
                            Id = new Guid("578c1771-e576-47e7-9c0e-7b84e250758d"),
                            Descricao = "Ceara",
                            Uf = "CE"
                        },
                        new
                        {
                            Id = new Guid("08e9b674-c360-4980-b52e-4ff7f5cc722c"),
                            Descricao = "Sao Paulo",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = new Guid("262e36b2-2951-48e3-9ccc-5c3e06d846b9"),
                            Descricao = "Rio de Janeiro",
                            Uf = "RJ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
