// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiron.Data.Context;

namespace Quiron.Data.Migrations
{
    [DbContext(typeof(QuironContext))]
    partial class QuironContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20159.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Quiron.Domain.Entities.Espaco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Espaco");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c221e33-bcb0-46ab-89df-2c53577dc70b"),
                            Descricao = "Salão de Festas"
                        },
                        new
                        {
                            Id = new Guid("442e9257-aa8f-4790-b8d5-ef74038ec504"),
                            Descricao = "Piscina"
                        },
                        new
                        {
                            Id = new Guid("9cb1e11d-9bb4-4abb-babd-4439a8da3751"),
                            Descricao = "Churrasqueira"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
